# Generated by Django 2.2.1 on 2019-06-18 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('import_xes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=255)),
                ('attribute', models.CharField(max_length=255)),
                ('dimension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='import_xes.Dimension', verbose_name='the sliced dimension')),
            ],
        ),
    ]
