# Generated by Django 2.2.1 on 2019-06-18 13:26

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.CharField(max_length=32)),
                ('values', djongo.models.fields.ListField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('xes_file', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessCube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='import_xes.EventLog')),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('attributes', djongo.models.fields.ArrayReferenceField(on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='import_xes.Attribute')),
                ('cube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='import_xes.ProcessCube')),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='import_xes.EventLog'),
        ),
    ]
