# Generated by Django 2.0.13 on 2019-05-04 10:16

from django.db import migrations, models
import djongo.models.fields
import import_xes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('event_log', djongo.models.fields.EmbeddedModelField(model_container=import_xes.models.EventLog, null=True)),
                ('parent', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace', djongo.models.fields.EmbeddedModelField(model_container=import_xes.models.Trace, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('xes_file', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_log', djongo.models.fields.EmbeddedModelField(model_container=import_xes.models.EventLog, null=True)),
            ],
        ),
    ]
