# Generated by Django 2.2.1 on 2019-06-21 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import_xes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='dtype',
            field=models.CharField(default=str, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dimension',
            name='cube',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='import_xes.ProcessCube'),
        ),
    ]
