# Generated by Django 2.2.1 on 2019-06-18 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('import_xes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumericalHierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_size', models.FloatField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='num_hierarchy', to='import_xes.Attribute')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='num_hierarchy', to='import_xes.Dimension')),
            ],
        ),
        migrations.CreateModel(
            name='DateHierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_size', models.IntegerField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_hierarchy', to='import_xes.Attribute')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_hierarchy', to='import_xes.Dimension')),
            ],
        ),
    ]
