#!/bin/sh

# set -o errexit
# set -o pipefail
# set -o nounset




if [ -z "${MONGO_INITDB_ROOT_USERNAME}" ]; then
    default_user='mongodb'
    export MONGO_INITDB_ROOT_USERNAME="${default_user}"
fi
export PCUBES_DATABASE_URL="mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb"

mongodb_ready() {
python << END
import sys

from pymongo import MongoClient

try:
    print('${PCUBES_DATABASE_URL}')
    MongoClient('${PCUBES_DATABASE_URL}')
except:
    sys.exit(-1)
sys.exit(0)

END
}
until mongodb_ready; do
  >&2 echo 'Waiting for MongoDB to become available...'
  sleep 1
done
>&2 echo 'MongoDB is available'

exec "$@"
