#!/bin/sh

# set -o errexit
# set -o pipefail
# set -o nounset




if [ -z "${MONGODB_USER}" ]; then
    base_postgres_image_default_user='mongodb'
    export MONGODB_USER="${base_postgres_image_default_user}"
fi
export PCUBES_DATABASE_URL="mongodb"

mongodb_ready() {
python << END
import sys

from pymongo import MongoClient

try:
    print('${PCUBES_DATABASE_URL}')
    MongoClient('${PCUBES_DATABASE_URL}')
except:
    sys.exit(-1)
sys.exit(0)

END
}
until mongodb_ready; do
  >&2 echo 'Waiting for MongoDB to become available...'
  sleep 1
done
>&2 echo 'MongoDB is available'

exec "$@"
